// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Usgm from "../../../index.js";

export declare namespace AddressesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AddressesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AddressesClient.Options>;

    constructor(options: AddressesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List your shipping and deposit addresses, optionally filtered by type
     *
     * @param {Usgm.AddressesListRequest} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.list()
     */
    public list(
        request: Usgm.AddressesListRequest = {},
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.AddressPageDto> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Usgm.AddressesListRequest = {},
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.AddressPageDto>> {
        const { limit, cursor, type: type_ } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            cursor,
            type: type_ != null ? type_ : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                "v1/addresses",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.AddressPageDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/addresses");
    }

    /**
     * Add a new shipping or check-deposit address to your account
     *
     * @param {Usgm.CreateAddressDto} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.create({
     *         type: "shipping",
     *         name: "name",
     *         line1: "line1",
     *         city: "city",
     *         state: "state",
     *         postal_code: "postal_code",
     *         country: "country",
     *         phone_number: "phone_number"
     *     })
     */
    public create(
        request: Usgm.CreateAddressDto,
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.AddressDto> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Usgm.CreateAddressDto,
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.AddressDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                "v1/addresses",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.AddressDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/addresses");
    }

    /**
     * Get your default address for a given type, shipping or deposit
     *
     * @param {Usgm.AddressesGetDefaultRequest} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.getdefault({
     *         type: "shipping"
     *     })
     */
    public getdefault(
        request: Usgm.AddressesGetDefaultRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.AddressDto> {
        return core.HttpResponsePromise.fromPromise(this.__getdefault(request, requestOptions));
    }

    private async __getdefault(
        request: Usgm.AddressesGetDefaultRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.AddressDto>> {
        const { type: type_ } = request;
        const _queryParams: Record<string, unknown> = {
            type: type_,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                "v1/addresses/default",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.AddressDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/addresses/default");
    }

    /**
     * Retrieve one shipping or deposit address by its id
     *
     * @param {Usgm.AddressesGetRequest} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.get({
     *         id: "id"
     *     })
     */
    public get(
        request: Usgm.AddressesGetRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.AddressDto> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Usgm.AddressesGetRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.AddressDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/addresses/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.AddressDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/addresses/{id}");
    }

    /**
     * Permanently delete an address; this is destructive and cannot be undone
     *
     * @param {Usgm.AddressesDeleteRequest} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Usgm.AddressesDeleteRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Usgm.AddressesDeleteRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/addresses/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/addresses/{id}");
    }

    /**
     * Update fields on an existing shipping or deposit address
     *
     * @param {Usgm.UpdateAddressDto} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Usgm.UpdateAddressDto,
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.AddressDto> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Usgm.UpdateAddressDto,
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.AddressDto>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/addresses/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.AddressDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/addresses/{id}");
    }

    /**
     * Make this address the default for its type, replacing the previous default
     *
     * @param {Usgm.AddressesSetDefaultRequest} request
     * @param {AddressesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.addresses.setdefault({
     *         id: "id"
     *     })
     */
    public setdefault(
        request: Usgm.AddressesSetDefaultRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.AddressDto> {
        return core.HttpResponsePromise.fromPromise(this.__setdefault(request, requestOptions));
    }

    private async __setdefault(
        request: Usgm.AddressesSetDefaultRequest,
        requestOptions?: AddressesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.AddressDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/addresses/${core.url.encodePathParam(id)}/default`,
            ),
            method: "PATCH",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.AddressDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/addresses/{id}/default");
    }
}
