// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Usgm from "../../../index.js";

export declare namespace BankAccountsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BankAccountsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BankAccountsClient.Options>;

    constructor(options: BankAccountsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List your bank accounts used for check deposits
     *
     * @param {Usgm.BankAccountsListRequest} request
     * @param {BankAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.bankAccounts.bankAccountsList()
     */
    public bankAccountsList(
        request: Usgm.BankAccountsListRequest = {},
        requestOptions?: BankAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.BankAccountPageDto> {
        return core.HttpResponsePromise.fromPromise(this.__bankAccountsList(request, requestOptions));
    }

    private async __bankAccountsList(
        request: Usgm.BankAccountsListRequest = {},
        requestOptions?: BankAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.BankAccountPageDto>> {
        const { limit, cursor } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            cursor,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                "v1/bank-accounts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.BankAccountPageDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/bank-accounts");
    }

    /**
     * Add a bank account for check deposits; account number is write-only
     *
     * @param {Usgm.CreateBankAccountDto} request
     * @param {BankAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.bankAccounts.bankAccountsCreate({
     *         bank_name: "bank_name",
     *         bank_state: "bank_state",
     *         account_number: "account_number"
     *     })
     */
    public bankAccountsCreate(
        request: Usgm.CreateBankAccountDto,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.BankAccountDto> {
        return core.HttpResponsePromise.fromPromise(this.__bankAccountsCreate(request, requestOptions));
    }

    private async __bankAccountsCreate(
        request: Usgm.CreateBankAccountDto,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.BankAccountDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                "v1/bank-accounts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.BankAccountDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank-accounts");
    }

    /**
     * Retrieve one bank account by id, returning only the last 4 digits
     *
     * @param {Usgm.BankAccountsGetRequest} request
     * @param {BankAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.bankAccounts.bankAccountsGet({
     *         id: "id"
     *     })
     */
    public bankAccountsGet(
        request: Usgm.BankAccountsGetRequest,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.BankAccountDto> {
        return core.HttpResponsePromise.fromPromise(this.__bankAccountsGet(request, requestOptions));
    }

    private async __bankAccountsGet(
        request: Usgm.BankAccountsGetRequest,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.BankAccountDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/bank-accounts/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.BankAccountDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/bank-accounts/{id}");
    }

    /**
     * Permanently delete a bank account; this is destructive and cannot be undone
     *
     * @param {Usgm.BankAccountsDeleteRequest} request
     * @param {BankAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.bankAccounts.bankAccountsDelete({
     *         id: "id"
     *     })
     */
    public bankAccountsDelete(
        request: Usgm.BankAccountsDeleteRequest,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__bankAccountsDelete(request, requestOptions));
    }

    private async __bankAccountsDelete(
        request: Usgm.BankAccountsDeleteRequest,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/bank-accounts/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/bank-accounts/{id}");
    }

    /**
     * Update the bank name, state, or account number on a bank account
     *
     * @param {Usgm.UpdateBankAccountDto} request
     * @param {BankAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.bankAccounts.bankAccountsUpdate({
     *         id: "id"
     *     })
     */
    public bankAccountsUpdate(
        request: Usgm.UpdateBankAccountDto,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.BankAccountDto> {
        return core.HttpResponsePromise.fromPromise(this.__bankAccountsUpdate(request, requestOptions));
    }

    private async __bankAccountsUpdate(
        request: Usgm.UpdateBankAccountDto,
        requestOptions?: BankAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.BankAccountDto>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/bank-accounts/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.BankAccountDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/bank-accounts/{id}");
    }
}
