// This file was auto-generated by Fern from our API Definition.

import type * as Usgm from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ShipmentsListRequest {
    /** Page size, capped at 100. */
    limit?: number;
    /** Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page. */
    cursor?: string;
    type?: Usgm.ShipmentsListRequestTypeItem | Usgm.ShipmentsListRequestTypeItem[];
    status?: Usgm.ShipmentsListRequestStatusItem | Usgm.ShipmentsListRequestStatusItem[];
}
