// This file was auto-generated by Fern from our API Definition.

import { AccountClient } from "./api/resources/account/client/Client.js";
import { AddressesClient } from "./api/resources/addresses/client/Client.js";
import { BankAccountsClient } from "./api/resources/bankAccounts/client/Client.js";
import { FoldersClient } from "./api/resources/folders/client/Client.js";
import { MailsClient } from "./api/resources/mails/client/Client.js";
import { SandboxClient } from "./api/resources/sandbox/client/Client.js";
import { ScansClient } from "./api/resources/scans/client/Client.js";
import { ShipmentsClient } from "./api/resources/shipments/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace UsgmClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class UsgmClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<UsgmClient.Options>;
    protected _mails: MailsClient | undefined;
    protected _scans: ScansClient | undefined;
    protected _shipments: ShipmentsClient | undefined;
    protected _folders: FoldersClient | undefined;
    protected _addresses: AddressesClient | undefined;
    protected _bankAccounts: BankAccountsClient | undefined;
    protected _account: AccountClient | undefined;
    protected _sandbox: SandboxClient | undefined;

    constructor(options: UsgmClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get mails(): MailsClient {
        return (this._mails ??= new MailsClient(this._options));
    }

    public get scans(): ScansClient {
        return (this._scans ??= new ScansClient(this._options));
    }

    public get shipments(): ShipmentsClient {
        return (this._shipments ??= new ShipmentsClient(this._options));
    }

    public get folders(): FoldersClient {
        return (this._folders ??= new FoldersClient(this._options));
    }

    public get addresses(): AddressesClient {
        return (this._addresses ??= new AddressesClient(this._options));
    }

    public get bankAccounts(): BankAccountsClient {
        return (this._bankAccounts ??= new BankAccountsClient(this._options));
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get sandbox(): SandboxClient {
        return (this._sandbox ??= new SandboxClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
