// This file was auto-generated by Fern from our API Definition.

export const UsgmEnvironment = {
    Default: "https://api.usglobalmail.com",
} as const;

export type UsgmEnvironment = typeof UsgmEnvironment.Default;
