// This file was auto-generated by Fern from our API Definition.

export const UsgmEnvironment = {
    Production: "https://api.usglobalmail.com",
    Sandbox: "https://api-sandbox.usglobalmail.com",
} as const;

export type UsgmEnvironment = typeof UsgmEnvironment.Production | typeof UsgmEnvironment.Sandbox;
