// This file was auto-generated by Fern from our API Definition.

export interface AccountDto {
    /** Account id (UUID). */
    id: string;
    name: string;
    email: string;
    phone_number?: (string | null) | undefined;
    /** Account status as reported by USGM (e.g. `APPROVED`, `SUSPENDED`). */
    status?: (string | null) | undefined;
    /** The PMB (private mailbox) number. Null until a mailbox is assigned. */
    box_number?: (string | null) | undefined;
    /** Registration date. */
    created_at: string;
}
