// This file was auto-generated by Fern from our API Definition.

export interface AddressDto {
    /** Address id (UUID). */
    id: string;
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    type: AddressDto.Type;
    /** Recipient name on the address. */
    name?: (string | null) | undefined;
    line1?: (string | null) | undefined;
    line2?: (string | null) | undefined;
    city?: (string | null) | undefined;
    state?: (string | null) | undefined;
    postal_code?: (string | null) | undefined;
    country?: (string | null) | undefined;
    line3?: (string | null) | undefined;
    phone_number?: (string | null) | undefined;
    tax_id?: (string | null) | undefined;
    /** The default address of its `type` — one per type. */
    is_default: boolean;
}

export namespace AddressDto {
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    export const Type = {
        Shipping: "shipping",
        Deposit: "deposit",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
