// This file was auto-generated by Fern from our API Definition.

export interface BankAccountPageDto {
    data: BankAccountPageDto.Data.Item[];
    /** Pass as `?cursor=` to fetch the next page. Null on the last page. */
    next_cursor: string | null;
    /** Total number of items matching this query across all pages. */
    total_count: number;
}

export namespace BankAccountPageDto {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Bank account id (UUID). */
            id: string;
            bank_name: string;
            bank_state: string;
            /** Last 4 characters of the account number. The full number is write-only and never returned. */
            account_number_last4: string;
        }
    }
}
