// This file was auto-generated by Fern from our API Definition.

export interface BankAccountDto {
    /** Bank account id (UUID). */
    id: string;
    bank_name: string;
    bank_state: string;
    /** Last 4 characters of the account number. The full number is write-only and never returned. */
    account_number_last4: string;
}
