// This file was auto-generated by Fern from our API Definition.

export interface FolderListDto {
    data: FolderListDto.Data.Item[];
}

export namespace FolderListDto {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Folder id (numeric string) — mail items reference it as `folder_id`. */
            id: string;
            name: string;
            /** Hex color like `#4BB94B`. */
            color?: (string | null) | undefined;
            created_on: string;
            updated_on: string;
        }
    }
}
