// This file was auto-generated by Fern from our API Definition.

export interface MailDetailDto {
    /** Mail item id (numeric string). */
    id: string;
    is_read: boolean;
    /** Lifecycle status as reported by the mailroom. */
    mail_status: string;
    mail_type: string;
    sender_name?: (string | null) | undefined;
    recipient_name?: (string | null) | undefined;
    /** When the item arrived at the facility. */
    arrival_date?: (string | null) | undefined;
    /** Photo of the item/envelope. */
    envelope_image_url?: (string | null) | undefined;
    quarantine_reason?: (string | null) | undefined;
    /** The scan requested for this item, when one exists. */
    scan?: (MailDetailDto.Scan | null) | undefined;
    /** Human-readable form of `mail_type` (e.g. "Large Letter"). */
    mail_type_label: string;
    /** Item dimensions, in inches. */
    measurement: MailDetailDto.Measurement;
    /** Item weight, in pounds. */
    weight: number;
    /** Inbound carrier tracking number, when one was captured. */
    tracking_number?: (string | null) | undefined;
    sender_address?: (string | null) | undefined;
    /** Whether the item is currently accruing storage charges. */
    has_storage_charges: boolean;
    folder?: (MailDetailDto.Folder | null) | undefined;
}

export namespace MailDetailDto {
    export interface Scan {
        /** Scan id — fetch it via `/v1/scans/{uuid}`. */
        uuid: string;
        /** `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`. */
        status: string;
        /** `SCAN_REQUEST` or `UNBOXING_REQUEST`. */
        category: string;
        /** Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling. */
        label?: (string | null) | undefined;
    }

    /**
     * Item dimensions, in inches.
     */
    export interface Measurement {
        /** Inches. */
        width: number;
        /** Inches. */
        height: number;
        /** Inches. */
        length: number;
    }

    export interface Folder {
        id: string;
        name: string;
        color?: (string | null) | undefined;
    }
}
