// This file was auto-generated by Fern from our API Definition.

export interface MailingAddressDto {
    /** The PMB (private mailbox) number — include it on every inbound mail piece. */
    box_number: string;
    line1?: (string | null) | undefined;
    line2?: (string | null) | undefined;
    line3?: (string | null) | undefined;
    city?: (string | null) | undefined;
    state?: (string | null) | undefined;
    postal_code?: (string | null) | undefined;
    country?: (string | null) | undefined;
    /** The complete address on one line, ready to hand out: "<line1> PMB <box>, <city>, <state>, <postal_code>, <country>". */
    formatted: string;
}
