// This file was auto-generated by Fern from our API Definition.

export interface MailPageDto {
    data: MailPageDto.Data.Item[];
    /** Pass as `?cursor=` to fetch the next page. Null on the last page. */
    next_cursor: string | null;
    /** Total number of items matching this query across all pages. */
    total_count: number;
}

export namespace MailPageDto {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Mail item id (numeric string). */
            id: string;
            /** Id of the folder the item is filed in — see `/v1/folders`. */
            folder_id?: (string | null) | undefined;
            is_read: boolean;
            /** Lifecycle status as reported by the mailroom. */
            mail_status: string;
            mail_type: string;
            sender_name?: (string | null) | undefined;
            recipient_name?: (string | null) | undefined;
            /** When the item arrived at the facility. */
            arrival_date?: (string | null) | undefined;
            /** Photo of the item/envelope. */
            envelope_image_url?: (string | null) | undefined;
            quarantine_reason?: (string | null) | undefined;
            /** The scan requested for this item, when one exists. */
            scan?: (Item.Scan | null) | undefined;
        }

        export namespace Item {
            export interface Scan {
                /** Scan id — fetch it via `/v1/scans/{uuid}`. */
                uuid: string;
                /** `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`. */
                status: string;
                /** `SCAN_REQUEST` or `UNBOXING_REQUEST`. */
                category: string;
                /** Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling. */
                label?: (string | null) | undefined;
            }
        }
    }
}
