// This file was auto-generated by Fern from our API Definition.

export interface ProblemDetailsDto {
    type: string;
    title: string;
    status: number;
    code: string;
    request_id: string;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: ProblemDetailsDto.Errors.Item[] | undefined;
}

export namespace ProblemDetailsDto {
    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            field: string;
            code?: string | undefined;
            message: string;
        }
    }
}
