// This file was auto-generated by Fern from our API Definition.

export interface ScanDto {
    /** Scan id (UUID). */
    id: string;
    /** Id of the scanned mail item (numeric string). */
    mail_id: string;
    /** `SCAN_REQUEST` (scan the item) or `UNBOXING_REQUEST` (open it and scan the contents). */
    type: string;
    /** `SUBMITTED`, `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`. */
    status: string;
    is_expedited: boolean;
    instruction?: (string | null) | undefined;
    /** Why the request was rejected. Null unless `status` is `REJECTED`. */
    reject_reason?: (string | null) | undefined;
    /** Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling. */
    label?: (string | null) | undefined;
    /** When the current `status` was reached — for completed scans, the completion time. */
    status_updated_at?: (string | null) | undefined;
    /** When the scan file is permanently deleted — download it before this date. Null when no deletion is scheduled. */
    auto_delete_on?: (string | null) | undefined;
    created_at: string;
    /** Last change of any kind — use `status_updated_at` for status timing. */
    updated_at: string;
}
