// This file was auto-generated by Fern from our API Definition.

export interface ScanSummaryDto {
    /** Short AI-generated label of the document (e.g. "Insurance"). */
    label: string | null;
    /** AI-generated summary of the document contents, one bullet point per entry. */
    summary: string[] | null;
}
