// This file was auto-generated by Fern from our API Definition.

export interface ScanFileDto {
    /** Short-lived signed download URL — fetch promptly, do not store it. */
    url: string;
    expires_at: string;
}
