// This file was auto-generated by Fern from our API Definition.

export interface ShipmentDetailDto {
    /** Shipment id (UUID). */
    id: string;
    type: ShipmentDetailDto.Type;
    /** Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment. */
    status: ShipmentDetailDto.Status;
    /** Carrier tracking number, once the shipment is on its way. */
    tracking_number?: (string | null) | undefined;
    /** Carrier service used (e.g. "FedEx International Priority"). */
    service_name?: (string | null) | undefined;
    /** Where it ships to. Only present for `shipment` and `check_deposit` types — returns go back to the sender and pickups happen at the facility. */
    destination?: (ShipmentDetailDto.Destination | null) | undefined;
    /** Number of mail items packed into the request. */
    item_count: number;
    /** The ship-out date the customer asked for. */
    requested_ship_date?: (string | null) | undefined;
    /** When the request was made. */
    created_on: string;
    /** `check_deposit` only. */
    deposit_check_slip_company_name?: (string | null) | undefined;
    /** Packing instructions given when the request was made. */
    instructions?: (string | null) | undefined;
    is_expedited: boolean;
    is_insured: boolean;
    /** Insured value in USD. Null when the shipment is not insured. */
    insured_amount?: (number | null) | undefined;
    /** Total declared customs value of the packed items, in USD. */
    declared_value: number;
    /** Why the request was rejected. Null unless `status` is `rejected`. */
    reject_reason?: (string | null) | undefined;
    mail_items: ShipmentDetailDto.MailItems.Item[];
}

export namespace ShipmentDetailDto {
    export const Type = {
        Shipment: "shipment",
        ReturnToSender: "return_to_sender",
        CheckDeposit: "check_deposit",
        Pickup: "pickup",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment. */
    export const Status = {
        Shipped: "shipped",
        InProgress: "in_progress",
        PaymentFailed: "payment_failed",
        Rejected: "rejected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Destination {
        /** Recipient name on the address. */
        name?: (string | null) | undefined;
        line1?: (string | null) | undefined;
        line2?: (string | null) | undefined;
        city?: (string | null) | undefined;
        state?: (string | null) | undefined;
        postal_code?: (string | null) | undefined;
        country?: (string | null) | undefined;
    }

    export type MailItems = MailItems.Item[];

    export namespace MailItems {
        export interface Item {
            /** Mail item id (numeric string). */
            id: string;
            mail_type: string;
            sender_name?: (string | null) | undefined;
            /** When the item arrived at the facility. */
            arrival_date?: (string | null) | undefined;
            /** Photo of the item/envelope. */
            envelope_image_url?: (string | null) | undefined;
        }
    }
}
