// This file was auto-generated by Fern from our API Definition.

export interface ShipmentPageDto {
    data: ShipmentPageDto.Data.Item[];
    /** Pass as `?cursor=` to fetch the next page. Null on the last page. */
    next_cursor: string | null;
    /** Total number of items matching this query across all pages. */
    total_count: number;
}

export namespace ShipmentPageDto {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Shipment id (UUID). */
            id: string;
            type: Item.Type;
            /** Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment. */
            status: Item.Status;
            /** Carrier tracking number, once the shipment is on its way. */
            tracking_number?: (string | null) | undefined;
            /** Carrier service used (e.g. "FedEx International Priority"). */
            service_name?: (string | null) | undefined;
            /** Where it ships to. Only present for `shipment` and `check_deposit` types — returns go back to the sender and pickups happen at the facility. */
            destination?: (Item.Destination | null) | undefined;
            /** Number of mail items packed into the request. */
            item_count: number;
            /** The ship-out date the customer asked for. */
            requested_ship_date?: (string | null) | undefined;
            /** When the request was made. */
            created_on: string;
            /** `check_deposit` only. */
            deposit_check_slip_company_name?: (string | null) | undefined;
        }

        export namespace Item {
            export const Type = {
                Shipment: "shipment",
                ReturnToSender: "return_to_sender",
                CheckDeposit: "check_deposit",
                Pickup: "pickup",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            /** Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment. */
            export const Status = {
                Shipped: "shipped",
                InProgress: "in_progress",
                PaymentFailed: "payment_failed",
                Rejected: "rejected",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];

            export interface Destination {
                /** Recipient name on the address. */
                name?: (string | null) | undefined;
                line1?: (string | null) | undefined;
                line2?: (string | null) | undefined;
                city?: (string | null) | undefined;
                state?: (string | null) | undefined;
                postal_code?: (string | null) | undefined;
                country?: (string | null) | undefined;
            }
        }
    }
}
