// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mail_id: "mail_id",
 *         type: "scan"
 *     }
 */
export interface CreateScanDto {
    mail_id: string;
    /** `scan` scans the item as-is; `open` opens it and scans the contents. */
    type: CreateScanDto.Type;
    instruction?: string;
    /** Expedited handling — may incur an extra charge. */
    is_expedited?: boolean;
}

export namespace CreateScanDto {
    /** `scan` scans the item as-is; `open` opens it and scans the contents. */
    export const Type = {
        Scan: "scan",
        Open: "open",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
