// This file was auto-generated by Fern from our API Definition.

import type * as Usgm from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ScansListRequest {
    /** Page size, capped at 100. */
    limit?: number;
    /** Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page. */
    cursor?: string;
    status?: Usgm.ScansListRequestStatusItem | Usgm.ScansListRequestStatusItem[];
    /** `scan` (scan the item) or `open` (open it and scan the contents). */
    type?: Usgm.ScansListRequestTypeItem | Usgm.ScansListRequestTypeItem[];
    mail_id?: string;
    search?: string;
    sort?: Usgm.ScansListRequestSort;
    scanned?: Usgm.ScansListRequestScanned;
}
