// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BankAccountsListRequest {
    /** Page size, capped at 100. */
    limit?: number;
    /** Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page. */
    cursor?: string;
}
