// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bank_name: "bank_name",
 *         bank_state: "bank_state",
 *         account_number: "account_number"
 *     }
 */
export interface CreateBankAccountDto {
    bank_name: string;
    bank_state: string;
    /** Full account number. Write-only — reads return `account_number_last4`. */
    account_number: string;
}
