// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateBankAccountDto {
    id: string;
    bank_name?: string;
    bank_state?: string;
    /** Full account number. Write-only — reads return `account_number_last4`. */
    account_number?: string;
}
