// This file was auto-generated by Fern from our API Definition.

export const AddressesGetDefaultRequestType = {
    Shipping: "shipping",
    Deposit: "deposit",
} as const;
export type AddressesGetDefaultRequestType =
    (typeof AddressesGetDefaultRequestType)[keyof typeof AddressesGetDefaultRequestType];
