// This file was auto-generated by Fern from our API Definition.

export const AddressesListRequestType = {
    Shipping: "shipping",
    Deposit: "deposit",
} as const;
export type AddressesListRequestType = (typeof AddressesListRequestType)[keyof typeof AddressesListRequestType];
