// This file was auto-generated by Fern from our API Definition.

export const ShipmentsListRequestTypeItem = {
    Shipment: "shipment",
    ReturnToSender: "return_to_sender",
    CheckDeposit: "check_deposit",
    Pickup: "pickup",
} as const;
export type ShipmentsListRequestTypeItem =
    (typeof ShipmentsListRequestTypeItem)[keyof typeof ShipmentsListRequestTypeItem];
