// This file was auto-generated by Fern from our API Definition.

export const ShipmentsListRequestStatusItem = {
    Shipped: "shipped",
    InProgress: "in_progress",
    PaymentFailed: "payment_failed",
    Rejected: "rejected",
} as const;
export type ShipmentsListRequestStatusItem =
    (typeof ShipmentsListRequestStatusItem)[keyof typeof ShipmentsListRequestStatusItem];
