// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Usgm from "../../../index.js";

export declare namespace FoldersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FoldersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FoldersClient.Options>;

    constructor(options: FoldersClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * All your mail folders, returned unpaginated
     *
     * @param {FoldersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.folders.list()
     */
    public list(requestOptions?: FoldersClient.RequestOptions): core.HttpResponsePromise<Usgm.FolderListDto> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: FoldersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.FolderListDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                "v1/folders",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.FolderListDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/folders");
    }

    /**
     * Create a new mail folder with a name and optional color
     *
     * @param {Usgm.CreateFolderDto} request
     * @param {FoldersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.folders.create({
     *         name: "name"
     *     })
     */
    public create(
        request: Usgm.CreateFolderDto,
        requestOptions?: FoldersClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.FolderDto> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Usgm.CreateFolderDto,
        requestOptions?: FoldersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.FolderDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                "v1/folders",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.FolderDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/folders");
    }

    /**
     * Retrieve one mail folder by its id
     *
     * @param {Usgm.FoldersGetRequest} request
     * @param {FoldersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.folders.get({
     *         id: "id"
     *     })
     */
    public get(
        request: Usgm.FoldersGetRequest,
        requestOptions?: FoldersClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.FolderDto> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Usgm.FoldersGetRequest,
        requestOptions?: FoldersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.FolderDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/folders/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.FolderDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/folders/{id}");
    }

    /**
     * Delete a folder and unfile its mail, which is not deleted
     *
     * @param {Usgm.FoldersDeleteRequest} request
     * @param {FoldersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.folders.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Usgm.FoldersDeleteRequest,
        requestOptions?: FoldersClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Usgm.FoldersDeleteRequest,
        requestOptions?: FoldersClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/folders/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/folders/{id}");
    }

    /**
     * Rename a folder or change its color
     *
     * @param {Usgm.UpdateFolderDto} request
     * @param {FoldersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.folders.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Usgm.UpdateFolderDto,
        requestOptions?: FoldersClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.FolderDto> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Usgm.UpdateFolderDto,
        requestOptions?: FoldersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.FolderDto>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/folders/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.FolderDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/folders/{id}");
    }
}
