// This file was auto-generated by Fern from our API Definition.

export const MailsListRequestMailTypeItem = {
    Letter: "letter",
    LargeLetter: "large_letter",
    Magazine: "magazine",
    Package: "package",
    Softpak: "softpak",
    Catalog: "catalog",
    Distribution: "distribution",
    Fulfillment: "fulfillment",
    Inventory: "inventory",
} as const;
export type MailsListRequestMailTypeItem =
    (typeof MailsListRequestMailTypeItem)[keyof typeof MailsListRequestMailTypeItem];
