// This file was auto-generated by Fern from our API Definition.

export const MailsListRequestSort = {
    Newest: "newest",
    Oldest: "oldest",
} as const;
export type MailsListRequestSort = (typeof MailsListRequestSort)[keyof typeof MailsListRequestSort];
