// This file was auto-generated by Fern from our API Definition.

export const MailsListRequestStatusItem = {
    Inbox: "inbox",
    Archived: "archived",
    Quarantine: "quarantine",
    DiscardRequest: "discard_request",
} as const;
export type MailsListRequestStatusItem = (typeof MailsListRequestStatusItem)[keyof typeof MailsListRequestStatusItem];
