// This file was auto-generated by Fern from our API Definition.

export const MailsListRequestArrived = {
    Week: "week",
    Month: "month",
    HalfYear: "half_year",
    Year: "year",
} as const;
export type MailsListRequestArrived = (typeof MailsListRequestArrived)[keyof typeof MailsListRequestArrived];
