// This file was auto-generated by Fern from our API Definition.

export const MailsListRequestIsRead = {
    True: "true",
    False: "false",
} as const;
export type MailsListRequestIsRead = (typeof MailsListRequestIsRead)[keyof typeof MailsListRequestIsRead];
