// This file was auto-generated by Fern from our API Definition.

export const MailsListRequestScanStatusItem = {
    InProcess: "in_process",
    Cancelled: "cancelled",
    Rejected: "rejected",
    Completed: "completed",
    Deleted: "deleted",
    Restoring: "restoring",
    None: "none",
} as const;
export type MailsListRequestScanStatusItem =
    (typeof MailsListRequestScanStatusItem)[keyof typeof MailsListRequestScanStatusItem];
