// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CompleteSandboxScanDto {
    id: string;
    /** Short document label the AI would produce, e.g. "Insurance". Set on the scan. */
    label?: string;
    /** Summary bullet points; retrievable via `GET /v1/scans/{id}/summary`. */
    summary?: string[];
}
