// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface SeedSandboxMailDto {
    sender_name?: string;
    /** Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`. */
    mail_type?: SeedSandboxMailDto.MailType;
    /** Item weight, in pounds. */
    weight?: number;
    /** Item dimensions, in inches. */
    measurement?: SeedSandboxMailDto.Measurement;
}

export namespace SeedSandboxMailDto {
    /** Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`. */
    export const MailType = {
        Letter: "LETTER",
        Largeletter: "LARGELETTER",
        Magazine: "MAGAZINE",
        Catalog: "CATALOG",
        Softpak: "SOFTPAK",
        Package: "PACKAGE",
    } as const;
    export type MailType = (typeof MailType)[keyof typeof MailType];

    /**
     * Item dimensions, in inches.
     */
    export interface Measurement {
        /** Inches. */
        width: number;
        /** Inches. */
        height: number;
        /** Inches. */
        length: number;
    }
}
