// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Usgm from "../../../index.js";

export declare namespace MailsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MailsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MailsClient.Options>;

    constructor(options: MailsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List your mail items with filtering, search, sorting and cursor pagination
     *
     * @param {Usgm.MailsListRequest} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.list()
     */
    public list(
        request: Usgm.MailsListRequest = {},
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailPageDto> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Usgm.MailsListRequest = {},
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailPageDto>> {
        const {
            limit,
            cursor,
            status,
            mail_type: mailType,
            folder_id: folderId,
            search,
            scan_status: scanStatus,
            sort,
            arrived,
            is_read: isRead,
        } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            cursor,
            status: Array.isArray(status) ? status.map((item) => item) : status != null ? status : undefined,
            mail_type: Array.isArray(mailType) ? mailType.map((item) => item) : mailType != null ? mailType : undefined,
            folder_id: folderId,
            search,
            scan_status: Array.isArray(scanStatus)
                ? scanStatus.map((item) => item)
                : scanStatus != null
                  ? scanStatus
                  : undefined,
            sort: sort != null ? sort : undefined,
            arrived: arrived != null ? arrived : undefined,
            is_read: isRead != null ? isRead : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                "v1/mails",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailPageDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/mails");
    }

    /**
     * Retrieve full detail for one mail item, including dimensions, weight and folder
     *
     * @param {Usgm.MailsGetRequest} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.get({
     *         id: "id"
     *     })
     */
    public get(
        request: Usgm.MailsGetRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailDetailDto> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Usgm.MailsGetRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailDetailDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/mails/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailDetailDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/mails/{id}");
    }

    /**
     * Mark the item read/unread and/or move it into a folder
     *
     * @param {Usgm.UpdateMailDto} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Usgm.UpdateMailDto,
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailDetailDto> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Usgm.UpdateMailDto,
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailDetailDto>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/mails/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailDetailDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v1/mails/{id}");
    }

    /**
     * Move the item out of your active inbox into the archive
     *
     * @param {Usgm.MailsArchiveRequest} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.archive({
     *         id: "id"
     *     })
     */
    public archive(
        request: Usgm.MailsArchiveRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailDetailDto> {
        return core.HttpResponsePromise.fromPromise(this.__archive(request, requestOptions));
    }

    private async __archive(
        request: Usgm.MailsArchiveRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailDetailDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/mails/${core.url.encodePathParam(id)}/archive`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailDetailDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/mails/{id}/archive");
    }

    /**
     * Restore an archived item back to its previous inbox status
     *
     * @param {Usgm.MailsUnarchiveRequest} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.unarchive({
     *         id: "id"
     *     })
     */
    public unarchive(
        request: Usgm.MailsUnarchiveRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailDetailDto> {
        return core.HttpResponsePromise.fromPromise(this.__unarchive(request, requestOptions));
    }

    private async __unarchive(
        request: Usgm.MailsUnarchiveRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailDetailDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/mails/${core.url.encodePathParam(id)}/unarchive`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailDetailDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/mails/{id}/unarchive");
    }

    /**
     * Request the mailroom to discard the physical item; destructive, reverse with undiscard within 7 days after the discard request. After 7 days the mail item will be permanently and securely shredded and discarded
     *
     * @param {Usgm.MailsDiscardRequest} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.discard({
     *         id: "id"
     *     })
     */
    public discard(
        request: Usgm.MailsDiscardRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailDetailDto> {
        return core.HttpResponsePromise.fromPromise(this.__discard(request, requestOptions));
    }

    private async __discard(
        request: Usgm.MailsDiscardRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailDetailDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/mails/${core.url.encodePathParam(id)}/discard`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailDetailDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/mails/{id}/discard");
    }

    /**
     * Cancel a pending discard request and keep the item
     *
     * @param {Usgm.MailsUndiscardRequest} request
     * @param {MailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.mails.undiscard({
     *         id: "id"
     *     })
     */
    public undiscard(
        request: Usgm.MailsUndiscardRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.MailDetailDto> {
        return core.HttpResponsePromise.fromPromise(this.__undiscard(request, requestOptions));
    }

    private async __undiscard(
        request: Usgm.MailsUndiscardRequest,
        requestOptions?: MailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.MailDetailDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Production,
                `v1/mails/${core.url.encodePathParam(id)}/undiscard`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.MailDetailDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/mails/{id}/undiscard");
    }
}
