// This file was auto-generated by Fern from our API Definition.

import type * as Usgm from "../../../../index.js";

/**
 * @example
 *     {
 *         type: "shipping"
 *     }
 */
export interface AddressesGetDefaultRequest {
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    type: Usgm.AddressesGetDefaultRequestType;
}
