// This file was auto-generated by Fern from our API Definition.

import type * as Usgm from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AddressesListRequest {
    /** Page size, capped at 100. */
    limit?: number;
    /** Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page. */
    cursor?: string;
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    type?: Usgm.AddressesListRequestType;
}
