// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         type: "shipping",
 *         name: "name",
 *         line1: "line1",
 *         city: "city",
 *         state: "state",
 *         postal_code: "postal_code",
 *         country: "country",
 *         phone_number: "phone_number"
 *     }
 */
export interface CreateAddressDto {
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    type: CreateAddressDto.Type;
    name: string;
    line1: string;
    line2?: string;
    line3?: string;
    city: string;
    state: string;
    postal_code: string;
    country: string;
    phone_number: string;
    tax_id?: string;
}

export namespace CreateAddressDto {
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    export const Type = {
        Shipping: "shipping",
        Deposit: "deposit",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
