// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateAddressDto {
    id: string;
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    type?: UpdateAddressDto.Type;
    name?: string;
    line1?: string;
    line2?: string;
    line3?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    country?: string;
    phone_number?: string;
    tax_id?: string;
}

export namespace UpdateAddressDto {
    /** `shipping` = a shipment destination; `deposit` = where check deposits are sent. */
    export const Type = {
        Shipping: "shipping",
        Deposit: "deposit",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
