// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Usgm from "../../../index.js";

export declare namespace ScansClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ScansClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ScansClient.Options>;

    constructor(options: ScansClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List your scan and open-and-scan requests, with filtering, search and pagination
     *
     * @param {Usgm.ScansListRequest} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.list()
     */
    public list(
        request: Usgm.ScansListRequest = {},
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanPageDto> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Usgm.ScansListRequest = {},
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanPageDto>> {
        const { limit, cursor, status, type: type_, mail_id: mailId, search, sort, scanned } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            cursor,
            status: Array.isArray(status) ? status.map((item) => item) : status != null ? status : undefined,
            type: Array.isArray(type_) ? type_.map((item) => item) : type_ != null ? type_ : undefined,
            mail_id: mailId,
            search,
            sort: sort != null ? sort : undefined,
            scanned: scanned != null ? scanned : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                "v1/scans",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanPageDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/scans");
    }

    /**
     * Request a scan or open-and-scan of a mail item; this is a billable action
     *
     * @param {Usgm.CreateScanDto} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.create({
     *         mail_id: "mail_id",
     *         type: "scan"
     *     })
     */
    public create(
        request: Usgm.CreateScanDto,
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanDto> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Usgm.CreateScanDto,
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                "v1/scans",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/scans");
    }

    /**
     * Retrieve one scan request by its id, including status and AI label
     *
     * @param {Usgm.ScansGetRequest} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.get({
     *         id: "id"
     *     })
     */
    public get(
        request: Usgm.ScansGetRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanDto> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Usgm.ScansGetRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/scans/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/scans/{id}");
    }

    /**
     * Permanently delete a scan and remove its stored file; this cannot be undone
     *
     * @param {Usgm.ScansDeleteRequest} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Usgm.ScansDeleteRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanDto> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Usgm.ScansDeleteRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/scans/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/scans/{id}");
    }

    /**
     * Return a short-lived signed URL to download the scanned document; fetch it promptly
     *
     * @param {Usgm.ScansFileRequest} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.file({
     *         id: "id"
     *     })
     */
    public file(
        request: Usgm.ScansFileRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanFileDto> {
        return core.HttpResponsePromise.fromPromise(this.__file(request, requestOptions));
    }

    private async __file(
        request: Usgm.ScansFileRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanFileDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/scans/${core.url.encodePathParam(id)}/file`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanFileDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/scans/{id}/file");
    }

    /**
     * Return the AI-generated label and bullet summary of the scanned document
     *
     * @param {Usgm.ScansSummaryRequest} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.summary({
     *         id: "id"
     *     })
     */
    public summary(
        request: Usgm.ScansSummaryRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanSummaryDto> {
        return core.HttpResponsePromise.fromPromise(this.__summary(request, requestOptions));
    }

    private async __summary(
        request: Usgm.ScansSummaryRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanSummaryDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/scans/${core.url.encodePathParam(id)}/summary`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanSummaryDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/scans/{id}/summary");
    }

    /**
     * Cancel a scan request you no longer need. Valid only for scan requests in in_process status
     *
     * @param {Usgm.ScansCancelRequest} request
     * @param {ScansClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Usgm.BadRequestError}
     * @throws {@link Usgm.UnauthorizedError}
     * @throws {@link Usgm.ForbiddenError}
     * @throws {@link Usgm.NotFoundError}
     * @throws {@link Usgm.ConflictError}
     * @throws {@link Usgm.UnprocessableEntityError}
     * @throws {@link Usgm.TooManyRequestsError}
     * @throws {@link Usgm.InternalServerError}
     *
     * @example
     *     await client.scans.cancel({
     *         id: "id"
     *     })
     */
    public cancel(
        request: Usgm.ScansCancelRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): core.HttpResponsePromise<Usgm.ScanDto> {
        return core.HttpResponsePromise.fromPromise(this.__cancel(request, requestOptions));
    }

    private async __cancel(
        request: Usgm.ScansCancelRequest,
        requestOptions?: ScansClient.RequestOptions,
    ): Promise<core.WithRawResponse<Usgm.ScanDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.UsgmEnvironment.Default,
                `v1/scans/${core.url.encodePathParam(id)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Usgm.ScanDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Usgm.BadRequestError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Usgm.UnauthorizedError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Usgm.ForbiddenError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Usgm.NotFoundError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 409:
                    throw new Usgm.ConflictError(_response.error.body as Usgm.ProblemDetailsDto, _response.rawResponse);
                case 422:
                    throw new Usgm.UnprocessableEntityError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Usgm.TooManyRequestsError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Usgm.InternalServerError(
                        _response.error.body as Usgm.ProblemDetailsDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.UsgmError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/scans/{id}/cancel");
    }
}
