// This file was auto-generated by Fern from our API Definition.

import type * as Usgm from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface MailsListRequest {
    /** Page size, capped at 100. */
    limit?: number;
    /** Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page. */
    cursor?: string;
    status?: Usgm.MailsListRequestStatusItem | Usgm.MailsListRequestStatusItem[];
    mail_type?: Usgm.MailsListRequestMailTypeItem | Usgm.MailsListRequestMailTypeItem[];
    folder_id?: number;
    search?: string;
    /** Filter by the item’s scan state; `none` selects items with no scan. */
    scan_status?: Usgm.MailsListRequestScanStatusItem | Usgm.MailsListRequestScanStatusItem[];
    sort?: Usgm.MailsListRequestSort;
    arrived?: Usgm.MailsListRequestArrived;
    is_read?: Usgm.MailsListRequestIsRead;
}
