// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateMailDto {
    id: string;
    is_read?: boolean;
    /** Move the item to this folder. Pass null to remove it from its folder. */
    folder_id?: string | null;
}
