// This file was auto-generated by Fern from our API Definition.

export const ScansListRequestTypeItem = {
    Scan: "scan",
    Open: "open",
} as const;
export type ScansListRequestTypeItem = (typeof ScansListRequestTypeItem)[keyof typeof ScansListRequestTypeItem];
