// This file was auto-generated by Fern from our API Definition.

export const ScansListRequestScanned = {
    Week: "week",
    Month: "month",
    HalfYear: "half_year",
    Year: "year",
} as const;
export type ScansListRequestScanned = (typeof ScansListRequestScanned)[keyof typeof ScansListRequestScanned];
