// This file was auto-generated by Fern from our API Definition.

export const ScansListRequestStatusItem = {
    Submitted: "submitted",
    InProcess: "in_process",
    Cancelled: "cancelled",
    Rejected: "rejected",
    Completed: "completed",
    Deleted: "deleted",
    Restoring: "restoring",
} as const;
export type ScansListRequestStatusItem = (typeof ScansListRequestStatusItem)[keyof typeof ScansListRequestStatusItem];
