// This file was auto-generated by Fern from our API Definition.

export const ScansListRequestSort = {
    Newest: "newest",
    Oldest: "oldest",
} as const;
export type ScansListRequestSort = (typeof ScansListRequestSort)[keyof typeof ScansListRequestSort];
